KOMODO_VARIANT ?= VANILLA
KOMODO_BASE_VERSION := 5.0
KOMODO_CODENAME := Tamara

# System version
KOMODO_BUILD_DATE := $(shell date -u +%Y%m%d)

KOMODO_PLATFORM_VERSION := 13

# Official Build
ifeq ($(KOMODO_BUILD_TYPE), OFFICIAL)
    KOMODO_BUILD_TYPE := OFFICIAL
else
    KOMODO_BUILD_TYPE := UNOFFICIAL
endif

# Gapps
ifeq ($(WITH_GAPPS), true)
     KOMODO_VARIANT := GAPPS
     $(call inherit-product, vendor/gapps/config.mk)
endif

KOMODO_VERSION := KomodoOS-$(KOMODO_BUILD_VERSION)-$(KOMODO_BUILD_TYPE)-$(KOMODO_BUILD)-$(KOMODO_VARIANT)-$(KOMODO_BUILD_DATE)
KOMODO_VERSION_PROP := thirteen
